spring:
  datasource:
    url: "jdbc:postgresql://101.133.231.235:15432/study?\
          ssl=true&\
          sslmode=verify-ca&\
          sslrootcert=D:/Workspace/config/postgresql/root-ca.crt&\
          sslkey=D:/Workspace/config/postgresql/client.key.pk8&\
          sslcert=D:/Workspace/config/postgresql/client.crt"
    username: chen
    hikari:
      max-lifetime: 60000
  data:
    redis:
      host: localhost
      port: 6379
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/appId/v2.0
        registration:
          azure-dev:
            provider: azure
            client-id: clientId
            client-secret: clientSecret
            redirect-uri: http://localhost:8848/
            scope:
              - xxxx
default-prefix: cache
default-expire: 14400s
default-time-zone: Asia/Shanghai

logging:
  level:
    xyz.chen.member.repository: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

config:
  default-system-id: 10000
  default-system-name: system
  default-oauth-role: 20000
  permit-all-urls:
    - /login
    - /login/oauth2Callback
    - /login/oauth2CallbackPost
    - /login/logout
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
