<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>esp32_host_app</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <Prefer32bit>false</Prefer32bit>
  </PropertyGroup>

  <PropertyGroup>
    <PresentMonSdkDir Condition="'$(PresentMonSdkDir)' == ''">C:\Program Files\Intel\PresentMon\SDK</PresentMonSdkDir>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.0.1.1416" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

  <ItemGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <Compile Remove="Monitor.cs" />
    <Compile Remove="WindowsAppRunner.cs" />
    <Compile Remove="DataFormat.Windows.cs" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(PresentMonSdkDir)\PresentMonAPI2Loader.dll')">
    <Content Include="$(PresentMonSdkDir)\PresentMonAPI2Loader.dll">
      <Link>PresentMonAPI2Loader.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
