// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_background;
extern lv_obj_t * ui_row1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_local_ip;
extern lv_obj_t * ui_local_ip_addr;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_real_fps;
extern lv_obj_t * ui_fps;
extern lv_obj_t * ui_cpu_info;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_gpu_name2;
extern lv_obj_t * ui_core_temp_info;
extern lv_obj_t * ui_cpu_core_temp;
extern lv_obj_t * ui_gpu_mem_mb3;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_gpu_power2;
extern lv_obj_t * ui_used_cpu_power;
extern lv_obj_t * ui_walt2;
extern lv_obj_t * ui_total_mem3;
extern lv_obj_t * ui_used_cpu_num;
extern lv_obj_t * ui_mem_mb4;
extern lv_obj_t * ui_gpu_freq_info2;
extern lv_obj_t * ui_cpu_freq;
extern lv_obj_t * ui_Mhz3;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_cpu_core1;
extern lv_obj_t * ui_cpu_core2;
extern lv_obj_t * ui_cpu_core3;
extern lv_obj_t * ui_cpu_core4;
extern lv_obj_t * ui_cpu_core5;
extern lv_obj_t * ui_cpu_core6;
extern lv_obj_t * ui_cpu_core7;
extern lv_obj_t * ui_cpu_core8;
extern lv_obj_t * ui_cpu_core9;
extern lv_obj_t * ui_cpu_core10;
extern lv_obj_t * ui_cpu_core11;
extern lv_obj_t * ui_cpu_core12;
extern lv_obj_t * ui_cpu_core13;
extern lv_obj_t * ui_cpu_core14;
extern lv_obj_t * ui_cpu_core15;
extern lv_obj_t * ui_cpu_core16;
extern lv_obj_t * ui_mem_info;
extern lv_obj_t * ui_mem_text;
extern lv_obj_t * ui_mem_name;
extern lv_obj_t * ui_total_mem;
extern lv_obj_t * ui_used_mem_number;
extern lv_obj_t * ui_mem_mb;
extern lv_obj_t * ui_total_mem1;
extern lv_obj_t * ui_used_mem;
extern lv_obj_t * ui_mem_mb1;
extern lv_obj_t * ui_used_mem_bar;
extern lv_obj_t * ui_gpu_info;
extern lv_obj_t * ui_gpu_text_info;
extern lv_obj_t * ui_gpu_name;
extern lv_obj_t * ui_gpu_temp;
extern lv_obj_t * ui_gpu_core_temp;
extern lv_obj_t * ui_gpu_mem_mb;
extern lv_obj_t * ui_gpu_power;
extern lv_obj_t * ui_uesd_gpu_power;
extern lv_obj_t * ui_walt;
extern lv_obj_t * ui_gpu_freq_info;
extern lv_obj_t * ui_gpu_freq;
extern lv_obj_t * ui_Mhz;
extern lv_obj_t * ui_gpu_core_v;
extern lv_obj_t * ui_gpu_core_volt;
extern lv_obj_t * ui_Volt;
extern lv_obj_t * ui_gpu_info_1;
extern lv_obj_t * ui_gpu_core_load_info;
extern lv_obj_t * ui_gpu_core_load;
extern lv_obj_t * ui_gpu_mem_mb1;
extern lv_obj_t * ui_gpu_load_bar;
extern lv_obj_t * ui_gpu_mem_name2;
extern lv_obj_t * ui_gpu_load_status;
extern lv_obj_t * ui_used_gpu_mem_number2;
extern lv_obj_t * ui_gpu_mem_info;
extern lv_obj_t * ui_gpu_mem_name;
extern lv_obj_t * ui_gpu_mem_freq_info;
extern lv_obj_t * ui_gpu_mem_freq;
extern lv_obj_t * ui_gpu_mem_mhz;
extern lv_obj_t * ui_gpu_mem_info_show;
extern lv_obj_t * ui_used_gpu_mem;
extern lv_obj_t * ui_Mhz2;
extern lv_obj_t * ui_gpu_mem_number;
extern lv_obj_t * ui_used_gpu_mem_number;
extern lv_obj_t * ui_mem_mb3;
extern lv_obj_t * ui_used_gpu_mem_bar;
// CUSTOM VARIABLES
extern lv_obj_t * uic_row1;
extern lv_obj_t * uic_Container1;
extern lv_obj_t * uic_local_ip;
extern lv_obj_t * uic_local_ip_addr;
extern lv_obj_t * uic_time;
extern lv_obj_t * uic_real_fps;
extern lv_obj_t * uic_fps;
extern lv_obj_t * uic_cpu_info;
extern lv_obj_t * uic_gpu_name;
extern lv_obj_t * uic_core_temp_info;
extern lv_obj_t * uic_cpu_core_temp;
extern lv_obj_t * uic_gpu_mem_mb;
extern lv_obj_t * uic_gpu_power;
extern lv_obj_t * uic_used_cpu_power;
extern lv_obj_t * uic_used_cpu_num;
extern lv_obj_t * uic_gpu_freq_info;
extern lv_obj_t * uic_Mhz;
extern lv_obj_t * uic_mem_info;
extern lv_obj_t * uic_used_mem_number;
extern lv_obj_t * uic_used_mem;
extern lv_obj_t * uic_used_mem_bar;
extern lv_obj_t * uic_gpu_info;
extern lv_obj_t * uic_gpu_text_info;
extern lv_obj_t * uic_gpu_name;
extern lv_obj_t * uic_gpu_temp;
extern lv_obj_t * uic_gpu_core_temp;
extern lv_obj_t * uic_gpu_mem_mb;
extern lv_obj_t * uic_gpu_power;
extern lv_obj_t * uic_uesd_gpu_power;
extern lv_obj_t * uic_gpu_freq_info;
extern lv_obj_t * uic_gpu_freq;
extern lv_obj_t * uic_Mhz;
extern lv_obj_t * uic_gpu_core_v;
extern lv_obj_t * uic_gpu_core_volt;
extern lv_obj_t * uic_Volt;
extern lv_obj_t * uic_gpu_info_1;
extern lv_obj_t * uic_gpu_core_load_info;
extern lv_obj_t * uic_gpu_core_load;
extern lv_obj_t * uic_gpu_mem_mb;
extern lv_obj_t * uic_gpu_load_bar;
extern lv_obj_t * uic_gpu_mem_name;
extern lv_obj_t * uic_gpu_load_status;
extern lv_obj_t * uic_used_gpu_mem_number;
extern lv_obj_t * uic_gpu_mem_info;
extern lv_obj_t * uic_gpu_mem_name;
extern lv_obj_t * uic_gpu_mem_freq_info;
extern lv_obj_t * uic_gpu_mem_freq;
extern lv_obj_t * uic_gpu_mem_mhz;
extern lv_obj_t * uic_gpu_mem_info_show;
extern lv_obj_t * uic_used_gpu_mem;
extern lv_obj_t * uic_Mhz;
extern lv_obj_t * uic_gpu_mem_number;
extern lv_obj_t * uic_used_gpu_mem_number;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
