// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_background = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_background);
    lv_obj_set_width(ui_background, lv_pct(98));
    lv_obj_set_height(ui_background, lv_pct(98));
    lv_obj_set_align(ui_background, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_background, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_background, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_background, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_background, lv_color_hex(0x080808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_background, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_row1 = lv_obj_create(ui_background);
    lv_obj_remove_style_all(ui_row1);
    lv_obj_set_width(ui_row1, lv_pct(100));
    lv_obj_set_height(ui_row1, lv_pct(25));
    lv_obj_set_x(ui_row1, -78);
    lv_obj_set_y(ui_row1, -36);
    lv_obj_set_align(ui_row1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_row1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_row1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_row1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_row1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 300);
    lv_obj_set_height(ui_Container1, lv_pct(100));
    lv_obj_set_x(ui_Container1, -326);
    lv_obj_set_y(ui_Container1, -178);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 18);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_local_ip = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_local_ip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_local_ip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_local_ip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_local_ip, "Local IP:  ");
    lv_obj_set_style_text_color(ui_local_ip, lv_color_hex(0x686868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_local_ip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_local_ip_addr = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_local_ip_addr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_local_ip_addr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_local_ip_addr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_local_ip_addr, "999.999.999.999:99999");
    lv_obj_set_style_text_color(ui_local_ip_addr, lv_color_hex(0x686868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_local_ip_addr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 50);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_align(ui_Container2, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "15:45:60");
    lv_obj_clear_flag(ui_time, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_row1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 200);
    lv_obj_set_height(ui_Container5, lv_pct(100));
    lv_obj_set_x(ui_Container5, -326);
    lv_obj_set_y(ui_Container5, -178);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_real_fps = lv_label_create(ui_Container5);
    lv_obj_set_height(ui_real_fps, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_flex_grow(ui_real_fps, 1);
    lv_obj_set_x(ui_real_fps, 4);
    lv_obj_set_y(ui_real_fps, 13);
    lv_obj_set_align(ui_real_fps, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_real_fps, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_real_fps, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_real_fps, "100");
    lv_obj_clear_flag(ui_real_fps, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_real_fps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_real_fps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_real_fps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_real_fps, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fps = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_fps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_fps, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_fps, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_fps, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_fps, "FPS");
    lv_obj_clear_flag(ui_fps, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_fps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_fps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fps, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cpu_info = lv_obj_create(ui_background);
    lv_obj_remove_style_all(ui_cpu_info);
    lv_obj_set_width(ui_cpu_info, lv_pct(100));
    lv_obj_set_height(ui_cpu_info, lv_pct(25));
    lv_obj_set_x(ui_cpu_info, -78);
    lv_obj_set_y(ui_cpu_info, -36);
    lv_obj_set_align(ui_cpu_info, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_cpu_info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_cpu_info, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_cpu_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container7 = lv_obj_create(ui_cpu_info);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, lv_pct(60));
    lv_obj_set_height(ui_Container7, lv_pct(100));
    lv_obj_set_x(ui_Container7, -133);
    lv_obj_set_y(ui_Container7, -127);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, lv_pct(50));
    lv_obj_set_x(ui_Container9, -160);
    lv_obj_set_y(ui_Container9, -58);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_name2 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_gpu_name2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpu_name2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpu_name2, -342);
    lv_obj_set_y(ui_gpu_name2, 5);
    lv_obj_set_align(ui_gpu_name2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_name2, "Core I5 13600K");
    lv_obj_set_style_text_color(ui_gpu_name2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_name2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_name2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_total_mem3 = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_total_mem3);
    lv_obj_set_width(ui_total_mem3, 95);
    lv_obj_set_height(ui_total_mem3, 50);
    lv_obj_set_x(ui_total_mem3, -69);
    lv_obj_set_y(ui_total_mem3, 72);
    lv_obj_set_align(ui_total_mem3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_total_mem3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_total_mem3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_total_mem3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_used_cpu_num = lv_label_create(ui_total_mem3);
    lv_obj_set_width(ui_used_cpu_num, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_used_cpu_num, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_used_cpu_num, LV_ALIGN_CENTER);
    lv_label_set_text(ui_used_cpu_num, "100");
    lv_obj_set_style_text_color(ui_used_cpu_num, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_used_cpu_num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_used_cpu_num, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mem_mb4 = lv_label_create(ui_total_mem3);
    lv_obj_set_width(ui_mem_mb4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mem_mb4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mem_mb4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mem_mb4, "% ");
    lv_obj_set_style_text_color(ui_mem_mb4, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mem_mb4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mem_mb4, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mem_mb4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mem_mb4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_core_temp_info = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_core_temp_info);
    lv_obj_set_width(ui_core_temp_info, 85);
    lv_obj_set_height(ui_core_temp_info, 50);
    lv_obj_set_x(ui_core_temp_info, -69);
    lv_obj_set_y(ui_core_temp_info, 72);
    lv_obj_set_align(ui_core_temp_info, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_core_temp_info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_core_temp_info, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_core_temp_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cpu_core_temp = lv_label_create(ui_core_temp_info);
    lv_obj_set_width(ui_cpu_core_temp, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_cpu_core_temp, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_cpu_core_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cpu_core_temp, "78");
    lv_obj_set_style_text_color(ui_cpu_core_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cpu_core_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cpu_core_temp, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_mem_mb3 = lv_label_create(ui_core_temp_info);
    lv_obj_set_width(ui_gpu_mem_mb3, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_gpu_mem_mb3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_mem_mb3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_mem_mb3, "°C");
    lv_obj_set_style_text_color(ui_gpu_mem_mb3, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_mem_mb3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_mem_mb3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gpu_mem_mb3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gpu_mem_mb3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(100));
    lv_obj_set_height(ui_Container8, lv_pct(50));
    lv_obj_set_x(ui_Container8, -257);
    lv_obj_set_y(ui_Container8, -87);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_power2 = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_gpu_power2);
    lv_obj_set_width(ui_gpu_power2, 105);
    lv_obj_set_height(ui_gpu_power2, 50);
    lv_obj_set_x(ui_gpu_power2, -69);
    lv_obj_set_y(ui_gpu_power2, 72);
    lv_obj_set_align(ui_gpu_power2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_power2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_power2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_power2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_gpu_power2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gpu_power2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gpu_power2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_used_cpu_power = lv_label_create(ui_gpu_power2);
    lv_obj_set_width(ui_used_cpu_power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_used_cpu_power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_used_cpu_power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_used_cpu_power, "222");
    lv_obj_set_style_text_color(ui_used_cpu_power, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_used_cpu_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_used_cpu_power, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_walt2 = lv_label_create(ui_gpu_power2);
    lv_obj_set_width(ui_walt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_walt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_walt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_walt2, "W");
    lv_obj_set_style_text_color(ui_walt2, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_walt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_walt2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_walt2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_walt2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_e_core_freq_group = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_e_core_freq_group);
    lv_obj_set_width(ui_e_core_freq_group, 155);
    lv_obj_set_height(ui_e_core_freq_group, 50);
    lv_obj_set_x(ui_e_core_freq_group, -69);
    lv_obj_set_y(ui_e_core_freq_group, 72);
    lv_obj_set_align(ui_e_core_freq_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_e_core_freq_group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_e_core_freq_group, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_e_core_freq_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_e_core_freq = lv_label_create(ui_e_core_freq_group);
    lv_obj_set_width(ui_e_core_freq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_e_core_freq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_e_core_freq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_e_core_freq, "2222");
    lv_obj_set_style_text_color(ui_e_core_freq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_e_core_freq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_e_core_freq, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_e_core_mhz = lv_label_create(ui_e_core_freq_group);
    lv_obj_set_width(ui_e_core_mhz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_e_core_mhz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_e_core_mhz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_e_core_mhz, "MHz");
    lv_obj_set_style_text_color(ui_e_core_mhz, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_e_core_mhz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_e_core_mhz, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_e_core_mhz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_e_core_mhz, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_p_core_freq_group = lv_obj_create(ui_Container8);
    lv_obj_remove_style_all(ui_p_core_freq_group);
    lv_obj_set_width(ui_p_core_freq_group, 155);
    lv_obj_set_height(ui_p_core_freq_group, 50);
    lv_obj_set_x(ui_p_core_freq_group, -69);
    lv_obj_set_y(ui_p_core_freq_group, 72);
    lv_obj_set_align(ui_p_core_freq_group, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_p_core_freq_group, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_p_core_freq_group, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_p_core_freq_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_p_core_freq = lv_label_create(ui_p_core_freq_group);
    lv_obj_set_width(ui_p_core_freq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_p_core_freq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_p_core_freq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_p_core_freq, "2222");
    lv_obj_set_style_text_color(ui_p_core_freq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_p_core_freq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_p_core_freq, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_p_core_mhz = lv_label_create(ui_p_core_freq_group);
    lv_obj_set_width(ui_p_core_mhz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_p_core_mhz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_p_core_mhz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_p_core_mhz, "MHz");
    lv_obj_set_style_text_color(ui_p_core_mhz, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_p_core_mhz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_p_core_mhz, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_p_core_mhz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_p_core_mhz, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_cpu_info);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(40));
    lv_obj_set_height(ui_Container6, lv_pct(100));
    lv_obj_set_x(ui_Container6, -307);
    lv_obj_set_y(ui_Container6, -87);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cpu_core1 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core1, 15);
    lv_obj_set_height(ui_cpu_core1, lv_pct(100));
    lv_obj_set_align(ui_cpu_core1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core1, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core1, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core2 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core2, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core2, 15);
    lv_obj_set_height(ui_cpu_core2, lv_pct(100));
    lv_obj_set_align(ui_cpu_core2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core2, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core2, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core3 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core3, 15);
    lv_obj_set_height(ui_cpu_core3, lv_pct(100));
    lv_obj_set_align(ui_cpu_core3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core3, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core3, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core4 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core4, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core4, 15);
    lv_obj_set_height(ui_cpu_core4, lv_pct(100));
    lv_obj_set_align(ui_cpu_core4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core4, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core4, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core5 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core5, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core5, 15);
    lv_obj_set_height(ui_cpu_core5, lv_pct(100));
    lv_obj_set_align(ui_cpu_core5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core5, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core5, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core6 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core6, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core6, 15);
    lv_obj_set_height(ui_cpu_core6, lv_pct(100));
    lv_obj_set_align(ui_cpu_core6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core6, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core6, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core7 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core7, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core7, 15);
    lv_obj_set_height(ui_cpu_core7, lv_pct(100));
    lv_obj_set_align(ui_cpu_core7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core7, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core7, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core8 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core8, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core8, 15);
    lv_obj_set_height(ui_cpu_core8, lv_pct(100));
    lv_obj_set_align(ui_cpu_core8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core8, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core8, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core9 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core9, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core9, 15);
    lv_obj_set_height(ui_cpu_core9, lv_pct(100));
    lv_obj_set_align(ui_cpu_core9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core9, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core9, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core10 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core10, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core10, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core10, 15);
    lv_obj_set_height(ui_cpu_core10, lv_pct(100));
    lv_obj_set_align(ui_cpu_core10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core10, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core10, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core10, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core11 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core11, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core11, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core11, 15);
    lv_obj_set_height(ui_cpu_core11, lv_pct(100));
    lv_obj_set_align(ui_cpu_core11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core11, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core11, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core11, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core12 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core12, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core12, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core12, 15);
    lv_obj_set_height(ui_cpu_core12, lv_pct(100));
    lv_obj_set_align(ui_cpu_core12, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core12, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core12, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core12, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core13 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core13, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core13, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core13, 15);
    lv_obj_set_height(ui_cpu_core13, lv_pct(100));
    lv_obj_set_align(ui_cpu_core13, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core13, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core13, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core13, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core14 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core14, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core14, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core14, 15);
    lv_obj_set_height(ui_cpu_core14, lv_pct(100));
    lv_obj_set_align(ui_cpu_core14, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core14, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core14, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core14, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core15 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core15, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core15, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core15, 15);
    lv_obj_set_height(ui_cpu_core15, lv_pct(100));
    lv_obj_set_align(ui_cpu_core15, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core15, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core15, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core15, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_cpu_core16 = lv_bar_create(ui_Container6);
    lv_bar_set_value(ui_cpu_core16, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_cpu_core16, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_cpu_core16, 15);
    lv_obj_set_height(ui_cpu_core16, lv_pct(100));
    lv_obj_set_align(ui_cpu_core16, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_cpu_core16, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cpu_core16, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cpu_core16, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_mem_info = lv_obj_create(ui_background);
    lv_obj_remove_style_all(ui_mem_info);
    lv_obj_set_width(ui_mem_info, lv_pct(100));
    lv_obj_set_height(ui_mem_info, lv_pct(13));
    lv_obj_set_x(ui_mem_info, -78);
    lv_obj_set_y(ui_mem_info, -36);
    lv_obj_set_align(ui_mem_info, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_mem_info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_mem_info, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mem_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mem_text = lv_obj_create(ui_mem_info);
    lv_obj_remove_style_all(ui_mem_text);
    lv_obj_set_height(ui_mem_text, 50);
    lv_obj_set_width(ui_mem_text, lv_pct(60));
    lv_obj_set_x(ui_mem_text, -271);
    lv_obj_set_y(ui_mem_text, 13);
    lv_obj_set_align(ui_mem_text, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_mem_text, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_mem_text, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mem_text, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mem_name = lv_label_create(ui_mem_text);
    lv_obj_set_width(ui_mem_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mem_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mem_name, -342);
    lv_obj_set_y(ui_mem_name, 5);
    lv_obj_set_align(ui_mem_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mem_name, "DDR4-3200");
    lv_obj_set_style_text_color(ui_mem_name, lv_color_hex(0x0080C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mem_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mem_name, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_total_mem = lv_obj_create(ui_mem_text);
    lv_obj_remove_style_all(ui_total_mem);
    lv_obj_set_width(ui_total_mem, 150);
    lv_obj_set_height(ui_total_mem, 50);
    lv_obj_set_x(ui_total_mem, -69);
    lv_obj_set_y(ui_total_mem, 72);
    lv_obj_set_align(ui_total_mem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_total_mem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_total_mem, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_total_mem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_used_mem_number = lv_label_create(ui_total_mem);
    lv_obj_set_width(ui_used_mem_number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_used_mem_number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_used_mem_number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_used_mem_number, "16234");
    lv_obj_set_style_text_color(ui_used_mem_number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_used_mem_number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_used_mem_number, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_used_mem_number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_used_mem_number, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mem_mb = lv_label_create(ui_total_mem);
    lv_obj_set_width(ui_mem_mb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mem_mb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mem_mb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mem_mb, " GB");
    lv_obj_set_style_text_color(ui_mem_mb, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mem_mb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mem_mb, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mem_mb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mem_mb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_total_mem1 = lv_obj_create(ui_mem_text);
    lv_obj_remove_style_all(ui_total_mem1);
    lv_obj_set_width(ui_total_mem1, 95);
    lv_obj_set_height(ui_total_mem1, 50);
    lv_obj_set_x(ui_total_mem1, -69);
    lv_obj_set_y(ui_total_mem1, 72);
    lv_obj_set_align(ui_total_mem1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_total_mem1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_total_mem1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_total_mem1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_used_mem = lv_label_create(ui_total_mem1);
    lv_obj_set_width(ui_used_mem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_used_mem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_used_mem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_used_mem, "100");
    lv_obj_set_style_text_color(ui_used_mem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_used_mem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_used_mem, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_used_mem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_used_mem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mem_mb1 = lv_label_create(ui_total_mem1);
    lv_obj_set_width(ui_mem_mb1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mem_mb1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mem_mb1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mem_mb1, "% ");
    lv_obj_set_style_text_color(ui_mem_mb1, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mem_mb1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mem_mb1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mem_mb1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mem_mb1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_used_mem_bar = lv_bar_create(ui_mem_info);
    lv_bar_set_value(ui_used_mem_bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_used_mem_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_used_mem_bar, lv_pct(40));
    lv_obj_set_height(ui_used_mem_bar, lv_pct(50));
    lv_obj_set_x(ui_used_mem_bar, 190);
    lv_obj_set_y(ui_used_mem_bar, 31);
    lv_obj_set_align(ui_used_mem_bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_used_mem_bar, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_used_mem_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_used_mem_bar, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_used_mem_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_gpu_info = lv_obj_create(ui_background);
    lv_obj_remove_style_all(ui_gpu_info);
    lv_obj_set_width(ui_gpu_info, lv_pct(100));
    lv_obj_set_height(ui_gpu_info, lv_pct(37));
    lv_obj_set_x(ui_gpu_info, -78);
    lv_obj_set_y(ui_gpu_info, -36);
    lv_obj_set_align(ui_gpu_info, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_info, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_gpu_info, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_text_info = lv_obj_create(ui_gpu_info);
    lv_obj_remove_style_all(ui_gpu_text_info);
    lv_obj_set_width(ui_gpu_text_info, lv_pct(100));
    lv_obj_set_height(ui_gpu_text_info, lv_pct(33));
    lv_obj_set_x(ui_gpu_text_info, -271);
    lv_obj_set_y(ui_gpu_text_info, 13);
    lv_obj_set_align(ui_gpu_text_info, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_text_info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_text_info, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_text_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_name = lv_label_create(ui_gpu_text_info);
    lv_obj_set_width(ui_gpu_name, 200);
    lv_obj_set_height(ui_gpu_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpu_name, -342);
    lv_obj_set_y(ui_gpu_name, 5);
    lv_obj_set_align(ui_gpu_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_name, "RTX 3060Ti");
    lv_obj_set_style_text_color(ui_gpu_name, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_name, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_temp = lv_obj_create(ui_gpu_text_info);
    lv_obj_remove_style_all(ui_gpu_temp);
    lv_obj_set_width(ui_gpu_temp, 85);
    lv_obj_set_height(ui_gpu_temp, 50);
    lv_obj_set_x(ui_gpu_temp, -69);
    lv_obj_set_y(ui_gpu_temp, 72);
    lv_obj_set_align(ui_gpu_temp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_temp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_temp, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_temp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_core_temp = lv_label_create(ui_gpu_temp);
    lv_obj_set_width(ui_gpu_core_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpu_core_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_core_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_core_temp, "67");
    lv_obj_set_style_text_color(ui_gpu_core_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_core_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_core_temp, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_mem_mb = lv_label_create(ui_gpu_temp);
    lv_obj_set_width(ui_gpu_mem_mb, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_gpu_mem_mb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_mem_mb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_mem_mb, "°C");
    lv_obj_set_style_text_color(ui_gpu_mem_mb, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_mem_mb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_mem_mb, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gpu_mem_mb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gpu_mem_mb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_power = lv_obj_create(ui_gpu_text_info);
    lv_obj_remove_style_all(ui_gpu_power);
    lv_obj_set_width(ui_gpu_power, 95);
    lv_obj_set_height(ui_gpu_power, 50);
    lv_obj_set_x(ui_gpu_power, -69);
    lv_obj_set_y(ui_gpu_power, 72);
    lv_obj_set_align(ui_gpu_power, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_power, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_power, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_uesd_gpu_power = lv_label_create(ui_gpu_power);
    lv_obj_set_width(ui_uesd_gpu_power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_uesd_gpu_power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_uesd_gpu_power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uesd_gpu_power, "222");
    lv_obj_set_style_text_color(ui_uesd_gpu_power, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uesd_gpu_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uesd_gpu_power, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_walt = lv_label_create(ui_gpu_power);
    lv_obj_set_width(ui_walt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_walt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_walt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_walt, "W");
    lv_obj_set_style_text_color(ui_walt, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_walt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_walt, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_walt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_walt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_freq_info = lv_obj_create(ui_gpu_text_info);
    lv_obj_remove_style_all(ui_gpu_freq_info);
    lv_obj_set_width(ui_gpu_freq_info, 155);
    lv_obj_set_height(ui_gpu_freq_info, 50);
    lv_obj_set_x(ui_gpu_freq_info, -69);
    lv_obj_set_y(ui_gpu_freq_info, 72);
    lv_obj_set_align(ui_gpu_freq_info, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_freq_info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_freq_info, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_freq_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_freq = lv_label_create(ui_gpu_freq_info);
    lv_obj_set_width(ui_gpu_freq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpu_freq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_freq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_freq, "2333");
    lv_obj_set_style_text_color(ui_gpu_freq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_freq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_freq, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mhz = lv_label_create(ui_gpu_freq_info);
    lv_obj_set_width(ui_Mhz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mhz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Mhz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mhz, "MHz");
    lv_obj_set_style_text_color(ui_Mhz, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Mhz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Mhz, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Mhz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Mhz, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_core_v = lv_obj_create(ui_gpu_text_info);
    lv_obj_remove_style_all(ui_gpu_core_v);
    lv_obj_set_width(ui_gpu_core_v, 135);
    lv_obj_set_height(ui_gpu_core_v, 50);
    lv_obj_set_x(ui_gpu_core_v, -69);
    lv_obj_set_y(ui_gpu_core_v, 72);
    lv_obj_set_align(ui_gpu_core_v, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_core_v, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_core_v, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_core_v, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_core_volt = lv_label_create(ui_gpu_core_v);
    lv_obj_set_width(ui_gpu_core_volt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpu_core_volt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_core_volt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_core_volt, "-");
    lv_obj_set_style_text_color(ui_gpu_core_volt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_core_volt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_core_volt, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Volt = lv_label_create(ui_gpu_core_v);
    lv_obj_set_width(ui_Volt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Volt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Volt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Volt, "mV");
    lv_obj_set_style_text_color(ui_Volt, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Volt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Volt, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Volt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Volt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_info_1 = lv_obj_create(ui_gpu_info);
    lv_obj_remove_style_all(ui_gpu_info_1);
    lv_obj_set_width(ui_gpu_info_1, lv_pct(100));
    lv_obj_set_height(ui_gpu_info_1, lv_pct(33));
    lv_obj_set_x(ui_gpu_info_1, -271);
    lv_obj_set_y(ui_gpu_info_1, 13);
    lv_obj_set_align(ui_gpu_info_1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_info_1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_info_1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_info_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_core_load_info = lv_obj_create(ui_gpu_info_1);
    lv_obj_remove_style_all(ui_gpu_core_load_info);
    lv_obj_set_width(ui_gpu_core_load_info, 100);
    lv_obj_set_height(ui_gpu_core_load_info, 50);
    lv_obj_set_x(ui_gpu_core_load_info, -69);
    lv_obj_set_y(ui_gpu_core_load_info, 72);
    lv_obj_set_align(ui_gpu_core_load_info, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_core_load_info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_core_load_info, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_core_load_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_gpu_core_load_info, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_gpu_core_load_info, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_gpu_core_load_info, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_core_load = lv_label_create(ui_gpu_core_load_info);
    lv_obj_set_width(ui_gpu_core_load, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpu_core_load, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_core_load, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_core_load, "100");
    lv_obj_set_style_text_color(ui_gpu_core_load, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_core_load, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_core_load, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_mem_mb1 = lv_label_create(ui_gpu_core_load_info);
    lv_obj_set_width(ui_gpu_mem_mb1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_gpu_mem_mb1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_mem_mb1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_mem_mb1, "%");
    lv_obj_set_style_text_color(ui_gpu_mem_mb1, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_mem_mb1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_mem_mb1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gpu_mem_mb1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gpu_mem_mb1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_load_bar = lv_bar_create(ui_gpu_info_1);
    lv_bar_set_value(ui_gpu_load_bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_gpu_load_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_gpu_load_bar, lv_pct(40));
    lv_obj_set_height(ui_gpu_load_bar, lv_pct(50));
    lv_obj_set_x(ui_gpu_load_bar, 190);
    lv_obj_set_y(ui_gpu_load_bar, 31);
    lv_obj_set_align(ui_gpu_load_bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_gpu_load_bar, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gpu_load_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_gpu_load_bar, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gpu_load_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_gpu_mem_name2 = lv_label_create(ui_gpu_info_1);
    lv_obj_set_width(ui_gpu_mem_name2, 150);
    lv_obj_set_height(ui_gpu_mem_name2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpu_mem_name2, -342);
    lv_obj_set_y(ui_gpu_mem_name2, 5);
    lv_obj_set_align(ui_gpu_mem_name2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_mem_name2, "PerfCap");
    lv_obj_set_style_text_color(ui_gpu_mem_name2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_mem_name2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_mem_name2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_load_status = lv_label_create(ui_gpu_info_1);
    lv_obj_set_width(ui_gpu_load_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpu_load_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_load_status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_load_status, "no load");
    lv_obj_set_style_text_color(ui_gpu_load_status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_load_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_gpu_load_status, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_load_status, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_used_gpu_mem_number2 = lv_textarea_create(ui_gpu_info_1);
    lv_obj_set_width(ui_used_gpu_mem_number2, lv_pct(20));
    lv_obj_set_height(ui_used_gpu_mem_number2, lv_pct(100));
    lv_obj_set_align(ui_used_gpu_mem_number2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_used_gpu_mem_number2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_used_gpu_mem_number2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_textarea_set_text(ui_used_gpu_mem_number2, "no load");
    lv_textarea_set_placeholder_text(ui_used_gpu_mem_number2, "Placeholder...");
    lv_obj_add_flag(ui_used_gpu_mem_number2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_used_gpu_mem_number2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_used_gpu_mem_number2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_used_gpu_mem_number2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_used_gpu_mem_number2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_used_gpu_mem_number2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_used_gpu_mem_number2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_gpu_mem_info = lv_obj_create(ui_gpu_info);
    lv_obj_remove_style_all(ui_gpu_mem_info);
    lv_obj_set_width(ui_gpu_mem_info, lv_pct(100));
    lv_obj_set_height(ui_gpu_mem_info, lv_pct(33));
    lv_obj_set_x(ui_gpu_mem_info, -271);
    lv_obj_set_y(ui_gpu_mem_info, 13);
    lv_obj_set_align(ui_gpu_mem_info, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_mem_info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_mem_info, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_mem_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_mem_name = lv_label_create(ui_gpu_mem_info);
    lv_obj_set_width(ui_gpu_mem_name, 150);
    lv_obj_set_height(ui_gpu_mem_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpu_mem_name, -342);
    lv_obj_set_y(ui_gpu_mem_name, 5);
    lv_obj_set_align(ui_gpu_mem_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_mem_name, "GDDR6");
    lv_obj_set_style_text_color(ui_gpu_mem_name, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_mem_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_mem_name, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_mem_freq_info = lv_obj_create(ui_gpu_mem_info);
    lv_obj_remove_style_all(ui_gpu_mem_freq_info);
    lv_obj_set_width(ui_gpu_mem_freq_info, 155);
    lv_obj_set_height(ui_gpu_mem_freq_info, 50);
    lv_obj_set_x(ui_gpu_mem_freq_info, -69);
    lv_obj_set_y(ui_gpu_mem_freq_info, 72);
    lv_obj_set_align(ui_gpu_mem_freq_info, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_mem_freq_info, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_mem_freq_info, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_mem_freq_info, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_gpu_mem_freq = lv_label_create(ui_gpu_mem_freq_info);
    lv_obj_set_width(ui_gpu_mem_freq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpu_mem_freq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_mem_freq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_mem_freq, "2222");
    lv_obj_set_style_text_color(ui_gpu_mem_freq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_mem_freq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_mem_freq, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_mem_mhz = lv_label_create(ui_gpu_mem_freq_info);
    lv_obj_set_width(ui_gpu_mem_mhz, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_gpu_mem_mhz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gpu_mem_mhz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpu_mem_mhz, "MHz");
    lv_obj_set_style_text_color(ui_gpu_mem_mhz, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpu_mem_mhz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpu_mem_mhz, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gpu_mem_mhz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gpu_mem_mhz, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_mem_info_show = lv_obj_create(ui_gpu_mem_info);
    lv_obj_remove_style_all(ui_gpu_mem_info_show);
    lv_obj_set_width(ui_gpu_mem_info_show, 135);
    lv_obj_set_height(ui_gpu_mem_info_show, 50);
    lv_obj_set_x(ui_gpu_mem_info_show, -69);
    lv_obj_set_y(ui_gpu_mem_info_show, 72);
    lv_obj_set_align(ui_gpu_mem_info_show, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_mem_info_show, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_mem_info_show, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_mem_info_show, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_used_gpu_mem = lv_label_create(ui_gpu_mem_info_show);
    lv_obj_set_width(ui_used_gpu_mem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_used_gpu_mem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_used_gpu_mem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_used_gpu_mem, "3333");
    lv_obj_set_style_text_color(ui_used_gpu_mem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_used_gpu_mem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_used_gpu_mem, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mhz2 = lv_label_create(ui_gpu_mem_info_show);
    lv_obj_set_width(ui_Mhz2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mhz2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Mhz2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mhz2, "MB");
    lv_obj_set_style_text_color(ui_Mhz2, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Mhz2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Mhz2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Mhz2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Mhz2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpu_mem_number = lv_obj_create(ui_gpu_mem_info);
    lv_obj_remove_style_all(ui_gpu_mem_number);
    lv_obj_set_width(ui_gpu_mem_number, 95);
    lv_obj_set_height(ui_gpu_mem_number, 50);
    lv_obj_set_x(ui_gpu_mem_number, -69);
    lv_obj_set_y(ui_gpu_mem_number, 72);
    lv_obj_set_align(ui_gpu_mem_number, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gpu_mem_number, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_gpu_mem_number, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_gpu_mem_number, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_used_gpu_mem_number = lv_label_create(ui_gpu_mem_number);
    lv_obj_set_width(ui_used_gpu_mem_number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_used_gpu_mem_number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_used_gpu_mem_number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_used_gpu_mem_number, "100");
    lv_obj_set_style_text_color(ui_used_gpu_mem_number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_used_gpu_mem_number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_used_gpu_mem_number, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mem_mb3 = lv_label_create(ui_gpu_mem_number);
    lv_obj_set_width(ui_mem_mb3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mem_mb3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_mem_mb3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mem_mb3, "% ");
    lv_obj_set_style_text_color(ui_mem_mb3, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mem_mb3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mem_mb3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mem_mb3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mem_mb3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_used_gpu_mem_bar = lv_bar_create(ui_gpu_mem_info);
    lv_bar_set_value(ui_used_gpu_mem_bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_used_gpu_mem_bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_used_gpu_mem_bar, lv_pct(25));
    lv_obj_set_height(ui_used_gpu_mem_bar, lv_pct(50));
    lv_obj_set_x(ui_used_gpu_mem_bar, 190);
    lv_obj_set_y(ui_used_gpu_mem_bar, 31);
    lv_obj_set_align(ui_used_gpu_mem_bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_used_gpu_mem_bar, lv_color_hex(0x3F2000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_used_gpu_mem_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_used_gpu_mem_bar, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_used_gpu_mem_bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    uic_row1 = ui_row1;
    uic_Container1 = ui_Container1;
    uic_local_ip = ui_local_ip;
    uic_local_ip_addr = ui_local_ip_addr;
    uic_time = ui_time;
    uic_real_fps = ui_real_fps;
    uic_fps = ui_fps;
    uic_cpu_info = ui_cpu_info;
    uic_gpu_name = ui_gpu_name2;
    uic_used_cpu_num = ui_used_cpu_num;
    uic_core_temp_info = ui_core_temp_info;
    uic_cpu_core_temp = ui_cpu_core_temp;
    uic_gpu_mem_mb = ui_gpu_mem_mb3;
    uic_gpu_power = ui_gpu_power2;
    uic_used_cpu_power = ui_used_cpu_power;
    uic_gpu_freq_info = ui_e_core_freq_group;
    uic_Mhz = ui_e_core_mhz;
    uic_gpu_freq_info = ui_p_core_freq_group;
    uic_Mhz = ui_p_core_mhz;
    uic_mem_info = ui_mem_info;
    uic_used_mem_number = ui_used_mem_number;
    uic_used_mem = ui_used_mem;
    uic_used_mem_bar = ui_used_mem_bar;
    uic_gpu_info = ui_gpu_info;
    uic_gpu_text_info = ui_gpu_text_info;
    uic_gpu_name = ui_gpu_name;
    uic_gpu_temp = ui_gpu_temp;
    uic_gpu_core_temp = ui_gpu_core_temp;
    uic_gpu_mem_mb = ui_gpu_mem_mb;
    uic_gpu_power = ui_gpu_power;
    uic_uesd_gpu_power = ui_uesd_gpu_power;
    uic_gpu_freq_info = ui_gpu_freq_info;
    uic_gpu_freq = ui_gpu_freq;
    uic_Mhz = ui_Mhz;
    uic_gpu_core_v = ui_gpu_core_v;
    uic_gpu_core_volt = ui_gpu_core_volt;
    uic_Volt = ui_Volt;
    uic_gpu_info_1 = ui_gpu_info_1;
    uic_gpu_core_load_info = ui_gpu_core_load_info;
    uic_gpu_core_load = ui_gpu_core_load;
    uic_gpu_mem_mb = ui_gpu_mem_mb1;
    uic_gpu_load_bar = ui_gpu_load_bar;
    uic_gpu_mem_name = ui_gpu_mem_name2;
    uic_gpu_load_status = ui_gpu_load_status;
    uic_used_gpu_mem_number = ui_used_gpu_mem_number2;
    uic_gpu_mem_info = ui_gpu_mem_info;
    uic_gpu_mem_name = ui_gpu_mem_name;
    uic_gpu_mem_freq_info = ui_gpu_mem_freq_info;
    uic_gpu_mem_freq = ui_gpu_mem_freq;
    uic_gpu_mem_mhz = ui_gpu_mem_mhz;
    uic_gpu_mem_info_show = ui_gpu_mem_info_show;
    uic_used_gpu_mem = ui_used_gpu_mem;
    uic_Mhz = ui_Mhz2;
    uic_gpu_mem_number = ui_gpu_mem_number;
    uic_used_gpu_mem_number = ui_used_gpu_mem_number;

}
