name: pull request check (esp32-board)

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened ]
    paths:
      - 'mcu/**'
      - '.github/workflows/pr-ci-esp32-board.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO
        run: |
          cd mcu/esp32-monitor
          pio run -e esp32dev