name: pull request check (esp32-host-cpp)

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened]
    paths:
      - 'app/**'
      - '.github/workflows/pr-ci-cpp.yaml'


jobs:
  build:
    name: Build with MSVC
    runs-on: windows-latest
    env:
      BASE_DIR: '${{ github.workspace }}'
      VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - uses: lukka/get-cmake@latest

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11

      - name: update
        run: |
          git fetch vcpkg --unshallow
          cd vcpkg
          git fetch --unshallow

      - name: Configure CMake
        run: |
          cd app/esp32_host_app
          cmake -B build -S . `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE="${{ env.BASE_DIR }}\vcpkg\scripts\buildsystems\vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build project
        working-directory: app/esp32_host_app
        run: cmake --build build --config Release

